// For authoring Nightwatch tests, see
// http://nightwatchjs.org/guide#usage

module.exports = {
  'default e2e tests': (browser) => {
    browser.url('http://localhost:8080')
    browser.waitForElementVisible('#app', 5000)

    browser.click('.v-toolbar__side-icon')
    browser.pause(500)
    browser.waitForElementVisible('#nav', 3000)
    browser.pause(500)
    browser.click('#crearCuentaNav')
    browser.pause(500)
    browser.setValue('#nombreCrearCuenta', 'Negocio')
    browser.pause(500)
    browser.click('#crearCuenta')
    browser.pause(500)
    browser.click('.v-toolbar__side-icon')
    browser.pause(500)
    browser.click('#Negocio')
    browser.pause(1000)

    browser.waitForElementVisible('#botonCategoria', 3000)
    browser.click('#botonCategoria')
    browser.waitForElementVisible('#formularioCategoria', 3000)
    browser.pause(500)
    browser.click('#selectorCategoria')
    browser.pause(500)
    browser.click('#app > div.v-menu__content.theme--light.v-menu__content--fixed.menuable__content__active.v-autocomplete__content > div > div > div:nth-child(1) > a')
    browser.pause(500)
    browser.setValue('#nombreCategoria', 'Comida')
    browser.pause(500)
    browser.click('#agregarCategoria')
    browser.pause(1000)

    browser.click('#botonIngreso')
    browser.pause(500)
    browser.waitForElementVisible('#formularioIngreso', 3000)
    browser.pause(500)
    browser.click('#selectorIngreso')
    browser.pause(500)
    browser.click('#app > div.v-menu__content.theme--light.v-menu__content--fixed.menuable__content__active.v-autocomplete__content > div > div > div:nth-child(1) > a')
    browser.pause(500)
    browser.click('#montoIngreso')
    browser.pause(500)
    browser.setValue('#montoIngreso', '5000')
    browser.pause(500)
    browser.click('#fechaCalendarioIngreso')
    browser.pause(500)
    browser.click('#datePickerIngreso > div.v-picker__body.theme--light > div > div.v-date-picker-table.v-date-picker-table--date.theme--light > table > tbody > tr:nth-child(3) > td:nth-child(4) > button')
    browser.pause(500)
    browser.click('#okCalendarioIngreso')
    browser.pause(500)
    browser.click('#agregarIngreso')
    browser.pause(1000)

    browser.click('#botonEgreso')
    browser.pause(500)
    browser.waitForElementVisible('#formularioEgreso', 3000)
    browser.pause(500)
    browser.click('#selectorEgreso')
    browser.pause(500)
    browser.click('#app > div.v-menu__content.theme--light.v-menu__content--fixed.menuable__content__active.v-autocomplete__content > div > div > div:nth-child(2) > a')
    browser.pause(500)
    browser.click('#montoEgreso')
    browser.pause(500)
    browser.setValue('#montoEgreso', '100')
    browser.pause(500)
    browser.click('#fechaCalendarioEgreso')
    browser.pause(500)
    browser.click('#datePickerEgreso > div.v-picker__body.theme--light > div > div.v-date-picker-table.v-date-picker-table--date.theme--light > table > tbody > tr:nth-child(3) > td:nth-child(6) > button')
    browser.pause(500)
    browser.click('#okCalendarioEgreso')
    browser.pause(500)
    browser.click('#agregarEgreso')
    browser.pause(1000)

    browser.click('#botonEgreso')
    browser.pause(500)
    browser.waitForElementVisible('#formularioEgreso', 3000)
    browser.pause(500)
    browser.click('#selectorEgreso')
    browser.pause(500)
    browser.click('#app > div.v-menu__content.theme--light.v-menu__content--fixed.menuable__content__active.v-autocomplete__content > div > div > div:nth-child(2) > a')
    browser.pause(500)
    browser.click('#montoEgreso')
    browser.pause(500)
    browser.setValue('#montoEgreso', '1000')
    browser.pause(500)
    browser.click('#fechaCalendarioEgreso')
    browser.pause(500)
    browser.click('#datePickerEgreso > div.v-picker__body.theme--light > div > div.v-date-picker-table.v-date-picker-table--date.theme--light > table > tbody > tr:nth-child(3) > td:nth-child(6) > button')
    browser.pause(500)
    browser.click('#okCalendarioEgreso')
    browser.pause(500)
    browser.click('#agregarEgreso')
    browser.pause(2000)

    browser.click('.v-toolbar__side-icon')
    browser.pause(500)
    browser.waitForElementVisible('#nav', 3000)
    browser.pause(500)
    browser.click('#crearCuentaNav')
    browser.pause(500)
    browser.setValue('#nombreCrearCuenta', 'Servicios')
    browser.pause(500)
    browser.click('#crearCuenta')
    browser.pause(1000)

    browser.click('.v-toolbar__side-icon')
    browser.pause(500)
    browser.click('#Negocio')
    browser.pause(1000)

    browser.click('#botonTransferencia')
    browser.pause(500)
    browser.waitForElementVisible('#formularioTransferencia', 3000)
    browser.pause(500)
    browser.click('#selectorCuentaTransferencia')
    browser.pause(500)
    browser.click('#app > div.v-menu__content.theme--light.v-menu__content--fixed.menuable__content__active.v-autocomplete__content > div > div > div > a')
    browser.pause(500)
    browser.click('#montoTransferencia')
    browser.pause(500)
    browser.setValue('#montoTransferencia', '200')
    browser.pause(500)
    browser.click('#fechaCalendarioTransferencia')
    browser.pause(500)
    browser.click('#datePickerTransferencia > div.v-picker__body.theme--light > div > div.v-date-picker-table.v-date-picker-table--date.theme--light > table > tbody > tr:nth-child(4) > td:nth-child(6) > button')
    browser.pause(500)
    browser.click('#okCalendarioTransferencia')
    browser.pause(500)
    browser.click('#agregarTransferencia')
    browser.pause(2000)

    browser.click('#botonReporte')
    browser.pause(500)
    browser.waitForElementVisible('#report', 3000)
    browser.pause(4000)

    browser.end()
  }
}
